// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALI_DAaWXx3MmoAK6mbLRMxJFu-6yjr4g',
    appId: '1:291504200025:web:0cf63aed34fe655e461448',
    messagingSenderId: '291504200025',
    projectId: 'badermkapp',
    authDomain: 'badermkapp.firebaseapp.com',
    storageBucket: 'badermkapp.appspot.com',
    measurementId: 'G-CD3XRTYNH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeiOtew8XyN7Df8NQkJu64xnC3cWiXcA',
    appId: '1:291504200025:android:3e8a6342fd8b0899461448',
    messagingSenderId: '291504200025',
    projectId: 'badermkapp',
    storageBucket: 'badermkapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCco7W-qVIHHJgTcSYbmFUWWl0pKFsHvpw',
    appId: '1:291504200025:ios:5545af5e3d2c43a3461448',
    messagingSenderId: '291504200025',
    projectId: 'badermkapp',
    storageBucket: 'badermkapp.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCco7W-qVIHHJgTcSYbmFUWWl0pKFsHvpw',
    appId: '1:291504200025:ios:4a79d849fa106260461448',
    messagingSenderId: '291504200025',
    projectId: 'badermkapp',
    storageBucket: 'badermkapp.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
